version: "2"
services:
  first-crud-db:
    container_name: first-crud-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "database"
      MYSQL_PASSWORD: "toor"
      MYSQL_ROOT_PASSWORD: "toor"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - first-crud-db-data:/var/lib/mysql
    networks:
      inner:
        aliases:
          - first-crud-db
  first-crud:
    container_name: first-crud
    build:
      context: ./
      dockerfile: Dockerfile.development
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - first-crud-db
    volumes:
      - "./:/usr/src/app"
      - "~/.ssh:/root/.ssh"
    networks:
      inner:
        aliases:
          - first-crud
networks:
  inner: {}
volumes:
  first-crud-db-data: {}
